### ISSUE TITLE
ElasticSearchQuery gets the total number of records

### ISSUE THREAD

**Issue by xueandfeng** [leonardosimoura/ElasticSearchQuery#1]
Hello, how do I get the total number of records for a paged query using ElasticSearchQuery?

**Comment by leonardosimoura** [comment]
I made some changes.  [#fa93923](https://github.com/leonardosimoura/ElasticSearchQuery/commit/fa93923f89083c5c5e90298fee6e3e63fd0092c9) 
Now just update to version 0.1.4 and use Count() to get the total number of records.
